# inside config/sidekiq.yml
concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>

max_retries: 25

queues:
  - default

scheduler:
  schedule:
    PurgeUnattachedBlobsJob:
      every: ["1d", first_in: "0s"]
    RefreshThreadsCredentialsJob:
      every: ["1d", first_in: "0s"]
